#include "opencv2/opencv.hpp"
#include "opencv2/imgcodecs.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>

#include"SkinDetector.h"

using namespace cv;

int main(int, char**) {
	String windowName = "videoCapture";

	VideoCapture videoCapture(0);
	
	if (!videoCapture.isOpened())
		return -1;

	namedWindow(windowName, 1);
	Mat frame;

	//Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
	//Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
	//pMOG2 = createBackgroundSubtractorMOG2(); //MOG2 approach

	SkinDetector mySkinDetector;

	while (true) {
		videoCapture >> frame;

		//pMOG2 -> apply(frame, fgMaskMOG2);
		frame = mySkinDetector.getSkin(frame);

		imshow(windowName, frame);
		
		if (waitKey(1) >= 0) break;
	}

	return 0;
}